// Package models contains the data structures used throughout the scoring engine.
package models

import (
	"time"
)

// InputData is the primary request payload for the scoring engine.
// It bundles the current user's claims with their historical database records
// to facilitate a comprehensive comparison.
type InputData struct {
	// UserData contains the real-time information provided in the current session.
	UserData UserData `json:"user_data"`
	
	// DBRecord contains the trusted historical data stored in the system.
	DBRecord DBRecord `json:"db_record"`
}

// OutputData represents the final verdict and audit report generated by the engine.
// It is designed to be returned to the caller or stored for compliance purposes.
type OutputData struct {
	// TicketID is a unique identifier for the scoring request (often linked to a support ticket).
	TicketID       int64     `json:"ticket_id"`
	
	// CreatedAt is the timestamp when the scoring process was initiated.
	CreatedAt      time.Time `json:"created_at"`
	
	// UpdatedAt is the timestamp when the calculation was finalized.
	UpdatedAt      time.Time `json:"updated_at"`
	
	// FinaPercentage is the human-readable final reliability score (e.g., "85.50%").
	FinaPercentage string    `json:"final_percentage"`
	
	// Metrics provides a high-level summary of the positive and negative scores.
	Metrics        Metrics   `json:"metrics"`
	
	// Details contains a granular breakdown of every calculation performed.
	// Omitted if empty to keep the response lean when debugging isn't required.
	Details        []CalcResult `json:"details,omitempty"`
}

// Metrics provides a simplified overview of the engine's findings, 
// separating positive verification from security-related penalties.
type Metrics struct {
	// Knowledge represents the cumulative "trust" score based on data matches.
	Knowledge    float64 `json:"knowledge"`
	
	// PenaltyScore represents the total risk factor calculated from anomalies.
	PenaltyScore float64 `json:"penalty_score"`
}