postgres:
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  database: "${DB_NAME}"
  ssl_mode: "${DB_SSLMODE}"

  max_conns: ${DB_MAX_CONNS}
  min_conns: ${DB_MIN_CONNS}
  max_idle_time: "${DB_IDLE_TIME}"
  max_lifetime: "${DB_LIFETIME}"
  health_check: "${DB_HEALTH_CHECK}"